const translaition = {
    en: {
        home:"Home",
        features:"Features",
        about:"About",
        services:"Services",
        contact:"Contact",
        english:"English",
        arabic:"arabic",
        landing_h1:"Welcome, To our company",
        landing_p:"Here Iam gonna share everything about my company.",
        features_quality_h2:"Gather Requirements",
        features_quality_p:"Create a list of customer requirements",
        more:"more",
        features_passion_h2:"Planning and Design",
        features_passion_p:"Gathering information and requirements, then creating the basic design to show how the site will work",
        features_time_h2:"Commencement of implementation",
        features_time_p:"the site will be implemented according to the agreed upon design",
        features_pass2_h2:"Quality assurance ",
        features_pass2_p:"The system is tested with the utmost precision to address any error or malfunction",
        features_time2_h2:"Launch and Deployment",
        features_time2_p:"When everything is working properly the site is launched",
        features_quality2_h2:"Complete Maintenance",
        features_quality2_p:"We provide complete maintenance and maintenance of your software ",
        about_p :"We have a specialized team of website developers and designers who are ready to work to put your company at the top through a strong and attractive website, ensuring that customers can access your company’s website easily and simply. We create websites that are visually attractive, fast, and most importantly, secure.",
        stats_h2 :"Our Awesome Stats",
        stats_years:"Years of experience",
        stats_completed:"Completed projects",
        stats_mail:"mail sent",
        stats_clients:"clients",
        services_h3_1:"Web Design",
        services_p_1:"Get an attractive and elegant design for your website, which will help you attract more visitors and give a distinctive impression to your customers",
        services_h3_2:"Phone applications",
        services_p_2:" We develop applications that meet companies' needs, improve the performance of companies' activities and provide innovative and effective solutions.",
        services_h3_3:"Websites maintenance",
        services_p_3:"We provide maintenance services for websites and electronic stores, updating them, and addressing any problems you may encounter with your site",
        services_h3_4:"SEO",
        services_p_4:" For companies that need cheap traffic and improve search results in a free way and without paying the cost of each visit.",
        services_h3_5:"Social media marketing",
        services_p_5:"For projects that need to display ads to the target market through social networks.",
        services_h3_6:" Other Services",
        services_p_6:"We provide services for anything you want related to developing, modifying or improving websites",
        contact_h2:"Do you have a project idea?",
        contact_p:"We are always excited to hear great and innovative ideas and help turn them into a distinguished and successful website",
        send:"send",
        quick_link:"Quick Link",
        categories:"categories"

    },
    
    ar: {
        home:"الرئيسية",
        features:"المميزات",
        about:"من نحن",
        services:"الخدمات",
        contact:"تواصل معنا",
        english:"الانكليزية",
        arabic:"العربية",
        landing_h1:"اهلا وسهلا بكم في شركتنا",
        landing_p:"هنا سأشارك كل شيء عن شركتي",
        features_quality_h2:"جمع متطلبات العملاء",
        features_quality_p:"إنشاء قائمة بمتطلبات العملاء",
        more:"المزيد",
        features_passion_h2:"التخطيط والتصميم",
        features_passion_p:"جمع المعلومات والمتطلبات، ثم إنشاء التصميم الأساسي لتوضيح كيفية عمل الموقع",
        features_time_h2:"البدء بالتنفيذ",
        features_time_p:"وسيتم تنفيذ الموقع حسب التصميم المتفق عليه",
        features_pass2_h2:"تأكيد الجودة",
        features_pass2_p:"يتم اختبار النظام بمنتهى الدقة لمعالجة أي خطأ أو عطل ",
        features_time2_h2:"الإطلاق والنشر",
        features_time2_p:"عندما يعمل كل شيء بشكل صحيح يتم إطلاق الموقع",
        features_quality2_h2:"صيانة كاملة",
        features_quality2_p:"نحن نقدم الصيانة الكاملة وصيانة البرامج الخاصة بك ",
        about_p :"لدينا فريق متخصص من مطوري ومصممي مواقع الويب على استعداد للعمل لوضع شركتك في القمة من خلال موقع ويب قوي وجذاب، مما يضمن وصول العملاء إلى موقع شركتك بسهولة وبساطة. نقوم بإنشاء مواقع ويب جذابة بصريًا، وسريعة، والأهم من ذلك، آمنة",
        stats_h2 :" احصائياتنا الرائعة",
        stats_years:"سنوات من الخبرة",
        stats_completed:"المشاريع المنجزة",
        stats_mail:"البريد المرسل",
        stats_clients:"عملاء",
        services_h3_1:"تصميم مواقع ويب",
        services_p_1:"احصل على تصميم جذاب وأنيق لموقعك الإلكتروني، مما يساعدك على جذب المزيد من الزوار ويعطي انطباع مميز لعملائك",
        services_h3_2:"تطبيقات الهاتف",
        services_p_2:"نقوم بتطوير التطبيقات التي تلبي احتياجات الشركات وتحسين أداء أنشطة الشركات وتقديم حلول مبتكرة وفعالة.",
        services_h3_3:"صيانة مواقع الويب",
        services_p_3:"نقدم خدمات صيانة المواقع والمتاجر الإلكترونية وتحديثها ومعالجة أي مشاكل قد تواجهك مع موقعك",
        services_h3_4:"تحسين محركات البحث",
        services_p_4:"للشركات التي تحتاج إلى ترافيك رخيص وتحسين نتائج البحث بطريقة مجانية ودون دفع تكلفة كل زيارة.",
        services_h3_5:"تسويق وسائل التواصل الاجتماعية",
        services_p_5:"للمشاريع التي تحتاج إلى عرض الإعلانات للسوق المستهدف عبر شبكات التواصل الاجتماعي",
        services_h3_6:"الخدمات الاخرى",
        services_p_6:"نحن نقدم خدمات لأي شيء تريده يتعلق بتطوير مواقع الويب أو تعديلها أو تحسينها",
        contact_h2:"هل لديك فكرة مشروع؟",
        contact_p:"نحن دائما متحمسون لسماع الأفكار الرائعة والمبتكرة والمساعدة في تحويلها إلى موقع متميز وناجح",
        send:"ارسال",
        quick_link:"روابط سريعة",
        categories:"فئات"
    }
}

export default translaition;